Snips.addText("de", :noip, "Ich finde die Adresse des Fernsehers nicht in der config Datei!")
Snips.addText("de", :nogpio, "Ich finde die Adresse des G P I O nicht in der config Datei!")
Snips.addText("de", :dunno, "Ich habe nicht verstanden was ich tun soll!")
Snips.addText("de", :switchon, "Ich schalte den Fernseher ein. Bitte einen Moment Geduld")
Snips.addText("de", :switchoff, "Ich schalte den Fernseher aus.")
Snips.addText("de", :already_on, "Der Fernseher ist bereits eingeschaltet")
Snips.addText("de", :tv_is_off, "Der Fernseher ist nicht eingeschaltet")
Snips.addText("de", :ok, "OK.")
Snips.addText("de", :mute, "Ton aus.")
Snips.addText("de", :mute, "Ich schalte den Ton aus.")
Snips.addText("de", :unmute, "Ich schalte den Ton an.")
Snips.addText("de", :channel, "Ich schalte um auf")
Snips.addText("de", :error_channel, "Ich habe den Sender nicht verstanden")
Snips.addText("de", :no_tv_in_room, "In diesem Raum gibt es keinen Fernseher!")

Snips.addText("de", :not_listen, "Ich höre jetzt nicht mehr zu!")
Snips.addText("de", :not_listen, "Ich höre jetzt weg!")


Snips.addText("en", :dunno, "I do not know what to do!")
