Snips.addText("de", :noip, "Ich finde die Adresse des Fernsehers nicht in der config Datei!")
Snips.addText("de", :nogpio, "Ich finde die Adresse des G P I O nicht in der config Datei!")
Snips.addText("de", :dunno, "Ich habe nicht verstanden was ich tun soll!")
Snips.addText("de", :switchon, "Ich schalte den Fernseher ein. Bitte einen Moment Geduld")
Snips.addText("de", :switchoff, "Ich schalte den Fernseher aus.")
Snips.addText("de", :ok, "OK.")
